dist: bionic
language: python
addons:
  firefox: latest
services:
  - xvfb
  - docker
python:
  - "3.6"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver
  - openssl aes-256-cbc -K $encrypted_7781db333198_key -iv $encrypted_7781db333198_iv -in deploy_id_rsa.enc -out deploy_id_rsa -d
install:
  - pip3 install -r requirements.txt
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build . -t qwanysh/lombard_crm
  - docker tag qwanysh/lombard_crm qwanysh/lombard_crm
  - docker push qwanysh/lombard_crm
script:
  - cd pawnshop_crm
  - python3 manage.py migrate
  - pytest -vvv --flake8
  - cd ..
deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: script
  script: fab -i deploy_id_rsa deploy
